Class {
	#name : 'Weapon',
	#superclass : 'Object',
	#category : 'IsLoopRockPaperScissors',
	#package : 'IsLoopRockPaperScissors'
}

{ #category : 'as yet unclassified' }
Weapon >> playAgainst: anotherWeapon [

	self subclassResponsibility
]

{ #category : 'as yet unclassified' }
Weapon >> playAgainstLizard [

	self subclassResponsibility
]

{ #category : 'as yet unclassified' }
Weapon >> playAgainstPaper [

	self subclassResponsibility
]

{ #category : 'as yet unclassified' }
Weapon >> playAgainstRock [

	self subclassResponsibility
]

{ #category : 'as yet unclassified' }
Weapon >> playAgainstScissors [

	self subclassResponsibility
]

{ #category : 'as yet unclassified' }
Weapon >> playAgainstSpock [

	self subclassResponsibility
]
